# Generated by Django 5.1.1 on 2024-12-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tek.document')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tek.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('document_1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_4', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_5', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_6', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_7', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_8', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.employee')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tek.service')),
            ],
        ),
    ]
