# Generated by Django 5.1.1 on 2025-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek', '0002_alter_document_document_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_1',
            new_name='calisma_ruhsati',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_2',
            new_name='faaliyet_belgesi',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_3',
            new_name='imza_sirkuleri',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_4',
            new_name='kurulus_sozlesmesi',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_5',
            new_name='oda_kayit_belgesi',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_6',
            new_name='sirketin_mali_bilgileri',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_7',
            new_name='ticaret_sicil_gazatesi',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='document_8',
            new_name='ticaret_sicil_tasdiknamesi',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vergi_levhasi',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='yetki_belgesi',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
