# Generated by Django 5.1.1 on 2025-01-12 19:42

import tek.file_validation
import tek.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek', '0003_rename_document_1_servicerequest_calisma_ruhsati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='calisma_ruhsati',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='faaliyet_belgesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='imza_sirkuleri',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='kurulus_sozlesmesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='oda_kayit_belgesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sirketin_mali_bilgileri',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ticaret_sicil_gazatesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ticaret_sicil_tasdiknamesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='vergi_levhasi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='yetki_belgesi',
            field=models.FileField(blank=True, null=True, upload_to=tek.models.upload_to_company_folder, validators=[tek.file_validation.validate_file_extension]),
        ),
    ]
