# Generated by Django 5.1.1 on 2025-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek', '0006_alter_servicehistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created')], default='Created', max_length=50, null=True),
        ),
    ]
