# Generated by Django 5.1.1 on 2025-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek', '0007_alter_servicehistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
    ]
