# Generated by Django 5.1.1 on 2025-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek', '0010_alter_servicerequest_status_delete_servicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='created', max_length=50, null=True),
        ),
    ]
