# Generated by Django 5.1.1 on 2024-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_user_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
